apply plugin: 'com.android.library'
def VERSION_CODE = 1
def VERSION_NAME = "1.0"

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion
    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode VERSION_CODE
        versionName VERSION_NAME

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"


        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    aaptOptions {
        cruncherEnabled = false
        useNewCruncher = false
    }

    sourceSets{
        main{
            jniLibs.srcDir 'libs'
            jni.srcDirs = []    //disable automatic ndk-build
        }
    }

    lintOptions {
        abortOnError false
        disable "Instantiatable"
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api project(':hhlibrary')
    api project(':videolibrary')
    api 'com.android.support.constraint:constraint-layout:1.0.2'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'


//    api 'com.github.wanliyang1990:wlmedia:2.0.0'
    api project(':wlmedia')
    api 'org.litepal.android:core:1.3.2'

 /*   compile 'com.tencent.jg:jg:1.1'     //腾讯推送
    compile 'com.tencent.tpns:tpns:1.2.1.3-release' //腾讯推送*/
}
