apply plugin: 'com.android.library'
def VERSION_CODE = 1
def VERSION_NAME = "1.0"
android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion
    aaptOptions.cruncherEnabled = false
    aaptOptions.useNewCruncher = false
    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode VERSION_CODE
        versionName VERSION_NAME
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            //根据需要 自行选择添加的对应cpu类型的.so库。
            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a'
            // 还可以添加 'x86', 'x86_64', 'mips', 'mips64'
        }

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        doNotStrip '*/mips/*.so'
        doNotStrip '*/mips64/*.so'
    }

  /*  sourceSets {

        main {
            jniLibs.srcDir 'libs'
            jni.srcDirs = []
        }
    }*/

    aaptOptions {
        cruncherEnabled = false
        useNewCruncher = false
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
    dexOptions {
        jumboMode true
    }
    compileOptions {

        sourceCompatibility org.gradle.api.JavaVersion.VERSION_1_8
        targetCompatibility org.gradle.api.JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api project(':hhlibrary')
    api 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    api 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1'
    api 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.github.chrisbanes:PhotoView:2.0.0'
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'
}
