apply plugin: 'com.android.library'

def VERSION_CODE = 1
def VERSION_NAME = "1.0"

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.minSdkVersion
        targetSdkVersion rootProject.targetSdkVersion
        versionCode VERSION_CODE
        versionName VERSION_NAME

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [moduleName: project.getName()]
            }
        }
        ndk {
            //设置支持的SO库架构
            /*abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64","armeabi"*/
            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a'
        }
        manifestPlaceholders = [
                XG_ACCESS_ID : "1500015815",
                XG_ACCESS_KEY : "AO3YNOCJ0AK2",
                HW_APPID: "103450845"

        ]

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    def system_dependencies = rootProject.ext.system_dependencies
    api system_dependencies.appcompat_v7
    api system_dependencies.support_v4
    api system_dependencies.cardview_v7
    api system_dependencies.palette_v7
    api system_dependencies.recyclerview_v7
    api system_dependencies.design
    api system_dependencies.rxjava
    api system_dependencies.rxandroid
    api system_dependencies.rxbinding
    api system_dependencies.glide
    api system_dependencies.gson
    // api  system_dependencies.fresco
    api system_dependencies.xutils
    compile('me.drakeet.multitype:multitype:2.2.2', {
        exclude group: 'com.android.support'
    })

    //com.nineoldandroids:library动画兼容库
    //fresco图片加载库(需要在项目的Application中自行初始化操作)
    //flyco.pageindicator 轮播指示灯库
    //rebound Android弹性动画库
    //Materialicons是Google推出的图标库,属于MaterialDesign工程的一部分
    compile('com.zhihu.android:matisse:0.4.3', {
        exclude group: 'com.android.support'
    })
    compile('ch.ielse:imagewatcher:1.0.3', {
        exclude group: 'com.android.support'
    })
    //路由


    api 'com.zhy:okhttputils:2.6.2'
    api 'com.baoyz.pullrefreshlayout:library:1.2.0'
    api 'de.hdodenhof:circleimageview:2.1.0'
    api 'id.zelory:compressor:2.1.0'
    api 'com.baoyz.swipemenulistview:library:1.3.0'
    api 'com.nineoldandroids:library:2.4.0'
    api 'com.facebook.fresco:fresco:0.12.0'
    api 'com.flyco.pageindicator:FlycoPageIndicator_Lib:1.0.0@aar'
    api 'com.facebook.rebound:rebound:0.3.8'
    api 'com.malinskiy:materialicons:1.0.2'
    api 'com.android.support.constraint:constraint-layout:1.0.2'
    api 'junit:junit:4.12'
    api 'com.google.code.gson:gson:2.6.2'
    api 'com.tbruyelle.rxpermissions2:rxpermissions:0.9.1@aar'
    api 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    api 'com.alibaba:arouter-api:1.3.1'
    /*api 'com.github.wendux:DSBridge-Android:3.0-SNAPSHOT'*/
    api project(':dsbridge')
    annotationProcessor 'com.alibaba:arouter-compiler:1.1.4'

    api 'org.greenrobot:eventbus:3.1.1'
    api 'com.tencent.jg:jg:1.1'     //腾讯推送
    api 'com.tencent.tpns:tpns:1.2.0.3-release' //腾讯推送
    api 'com.tencent.tpns:xiaomi:1.2.1.0-release'//小米推送
    api 'com.tencent.tpns:huawei:1.2.2.0-release'  //华为推送
    api 'com.tencent.tpns:meizu:1.2.2.0-release'//meizu 推送
    api 'com.tencent.tpns:oppo:1.2.2.0-release'//oppo 推送
    api 'com.squareup.okhttp:okhttp:2.7.2'
    api 'com.rxjava.rxhttp:rxhttp:1.1.6'
    api 'com.tencent.mm.opensdk:wechat-sdk-android:+'
    annotationProcessor 'com.rxjava.rxhttp:rxhttp-compiler:1.1.6'

    api 'com.tencent.bugly:crashreport:4.0.4' //其中latest.release指代最新Bugly SDK版本号，也可以指定明确的版本号，例如4.0.3


}
